add_test( [==[unittests.Random Test Bit]==] /mnt/d/github/bitpacker/buildlinux/bin/tests [==[Random Test Bit]==] [==[--reporter xml]==] [==[--out /mnt/d/github/bitpacker/buildlinux/test/./unittests.Random_Test_Bit.xml]==])
set_tests_properties( [==[unittests.Random Test Bit]==] PROPERTIES WORKING_DIRECTORY /mnt/d/github/bitpacker/buildlinux/test)
add_test( [==[unittests.Sanity Check Buffer Read]==] /mnt/d/github/bitpacker/buildlinux/bin/tests [==[Sanity Check Buffer Read]==] [==[--reporter xml]==] [==[--out /mnt/d/github/bitpacker/buildlinux/test/./unittests.Sanity_Check_Buffer_Read.xml]==])
set_tests_properties( [==[unittests.Sanity Check Buffer Read]==] PROPERTIES WORKING_DIRECTORY /mnt/d/github/bitpacker/buildlinux/test)
add_test( [==[unittests.Sanity Check Buffer Write]==] /mnt/d/github/bitpacker/buildlinux/bin/tests [==[Sanity Check Buffer Write]==] [==[--reporter xml]==] [==[--out /mnt/d/github/bitpacker/buildlinux/test/./unittests.Sanity_Check_Buffer_Write.xml]==])
set_tests_properties( [==[unittests.Sanity Check Buffer Write]==] PROPERTIES WORKING_DIRECTORY /mnt/d/github/bitpacker/buildlinux/test)
add_test( [==[unittests.Bits Required Util]==] /mnt/d/github/bitpacker/buildlinux/bin/tests [==[Bits Required Util]==] [==[--reporter xml]==] [==[--out /mnt/d/github/bitpacker/buildlinux/test/./unittests.Bits_Required_Util.xml]==])
set_tests_properties( [==[unittests.Bits Required Util]==] PROPERTIES WORKING_DIRECTORY /mnt/d/github/bitpacker/buildlinux/test)
add_test( [==[unittests.Stream Read And Write Random Structure]==] /mnt/d/github/bitpacker/buildlinux/bin/tests [==[Stream Read And Write Random Structure]==] [==[--reporter xml]==] [==[--out /mnt/d/github/bitpacker/buildlinux/test/./unittests.Stream_Read_And_Write_Random_Structure.xml]==])
set_tests_properties( [==[unittests.Stream Read And Write Random Structure]==] PROPERTIES WORKING_DIRECTORY /mnt/d/github/bitpacker/buildlinux/test)
set( tests_TESTS [==[unittests.Random Test Bit]==] [==[unittests.Sanity Check Buffer Read]==] [==[unittests.Sanity Check Buffer Write]==] [==[unittests.Bits Required Util]==] [==[unittests.Stream Read And Write Random Structure]==])
